//error handling
try{
    a=12;
    b=0;
    c=a/b
    console.log(c);
}
    catch(e)
    {
        console.log("error is:"+e);
    }
